chore: 🧹 Resolve CircleCI GCP Secrets problem (autofix)
### Check description:
Finds usage of static credentials for GCP in CircleCI configurations, and helps replace them with passwordless access.

### Problem summary:
Uses static credentials from [gcloud-registry]

> TypeError: Invalid Version: ~0.15
>     at new SemVer (/Users/daniellamando/Code/fh/repo-nanny/node_modules/semver/classes/semver.js:38:13)
>     at compare (/Users/daniellamando/Code/fh/repo-nanny/node_modules/semver/functions/compare.js:3:3)
>     at gte (/Users/daniellamando/Code/fh/repo-nanny/node_modules/semver/functions/gte.js:2:30)
>     at server/checks/circleci-gcp-secrets.ts:141:13
>     at /Users/daniellamando/.meteor/packages/promise/.0.12.2.1i3x3qn.ujy9g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

#### In `.circleci/config.yml`:
* GCR Push Orb should authenticate with OIDC (line 19)
* Job "gcp-gcr/build-and-push-image" should use passwordless access to GCR (line 16)
* 'circleci/gcp-gcr' only supports passwordless access since 0.16 (line 3)

### :broom: Authored using Repo Nanny
https://work.pug-vibes.ts.net:3443/repos/certspotter